- name: Install git
  apt: pkg=git
  sudo: yes

- name: Push global config file
  template:
    src=gitconfig.j2
    dest=/etc/gitconfig
    mode=0644
  sudo: yes

- name: Clone all repositories to cache and checkout them to the HEAD
  git:
    repo={{ item.value }}
    dest={{ git.path }}/{{ item.key }}
    accept_hostkey=yes
    update=yes
    version=HEAD
    force=yes
  with_dict: git.repositories
